allowBuilds:
  esbuild: true
  lightningcss: true
  sharp: true
  better-sqlite3: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
